# Data Analysis Test

Use file `./ref/crop_data.csv` for input

Use `pandas` lib

Write your code and display readable result

In [1]:
import pandas as pd

In [2]:
# read csv file

df = pd.read_csv("./ref/crop_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   crop_year         11914 non-null  object 
 1   year              11914 non-null  int64  
 2   product           11914 non-null  object 
 3   province          11914 non-null  object 
 4   area_plant_rai    11769 non-null  float64
 5   area_harvest_rai  11728 non-null  float64
 6   production_ton    11692 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 651.7+ KB


### Example Question

How many "ยางพารา" produced in whole country ("ทั้งประเทศ")


In [3]:
# How many "ยางพารา" produced in whole country ("ทั้งประเทศ")
new_df = df.loc[
    (df["product"] == "ยางพารา" ) &
    (df["province"] == "ทั้งประเทศ") 
]
sum(new_df["production_ton"])


47686839.0

In [ ]:
# Data Explore
print(df)

      crop_year  year         product    province  area_plant_rai  \
0       2549/50  2550        ข้าวนาปี  ทั้งประเทศ      57541825.0   
1       2550/51  2551        ข้าวนาปี  ทั้งประเทศ      57385921.0   
2       2551/52  2552        ข้าวนาปี  ทั้งประเทศ      57422337.0   
3       2552/53  2553        ข้าวนาปี  ทั้งประเทศ      57497441.0   
4       2553/54  2554        ข้าวนาปี  ทั้งประเทศ      64574071.0   
...         ...   ...             ...         ...             ...   
11909      2558  2558  ข้าวโพดฝักอ่อน    นราธิวาส           349.0   
11910      2559  2559  ข้าวโพดฝักอ่อน    นราธิวาส           506.0   
11911      2560  2560  ข้าวโพดฝักอ่อน    นราธิวาส           441.0   
11912      2561  2561  ข้าวโพดฝักอ่อน    นราธิวาส           534.0   
11913      2562  2562  ข้าวโพดฝักอ่อน    นราธิวาส           472.0   

       area_harvest_rai  production_ton  
0            53500163.0      23108401.0  
1            53892143.0      23582596.0  
2            54385144.0      23508833.0  
3  

### Question 1

How many "ข้าวนาปี" produced in "ยะลา" between year 2550 - 2553


In [7]:
# Write you code and display question 1 result here.

# Filter the DataFrame based on the conditions
filtered_df = df[
    (df['product'] == 'ข้าวนาปี') & 
    (df['province'] == 'ยะลา') & 
    (df['year'].between(2550, 2553))
]

# Count the number of records
count_records = filtered_df.shape[0]

print(f"Count of records: {count_records}")

Count of records: 4


### Question 2

Calculate harvest rate of "ข้าวนาปี" in whole country

_harvest rate = area_harvest_rai / area_plant_rai_

In [10]:
# Write you code and display question 2 result here.
# replace with your code

filtered_df = df[
    (df['product'] == 'ข้าวนาปี') &
    (df['province'] == 'ทั้งประเทศ')
]

area_harvest_rai = filtered_df['area_harvest_rai'].sum()   
area_plant_rai = filtered_df['area_plant_rai'].sum()
harvest_rate = area_harvest_rai / area_plant_rai

print('area_harvest_rai', area_harvest_rai)
print('area_plant_rai', area_plant_rai)
print('harvest_rate', harvest_rate)

area_harvest_rai 730340255.0
area_plant_rai 783456906.0
harvest_rate 0.9322022046225986


### Question 3

Calculate total profit of "ข้าวโพดฝักอ่อน" produced in "ภาคเหนือ" from year 2555 to 2562
- profit rate in year 2555 - year 2559 is 50% (selling price is 50THB/kg.)
- profit rate in year 2560 - year 2562 is 30% (selling price is 120THB/kg.)
- assume all product was sold out every year.

In [16]:
# Write you code and display question 3 result here.

# Filter rows for the specified product and region
filtered_df = df[
    (df['product'] == 'ข้าวโพดฝักอ่อน') &
    (df['province'] == 'ภาคเหนือ') &
    (df['year'].between(2555, 2562))
]


# Calculate profit for years 2555-2559
df_2555_2559 = filtered_df[filtered_df['year'].between(2555, 2559)]
profit_2555_2559 = (df_2555_2559['production_ton'] * 1000) * 50 * 0.5
#print(f"Profit for 2555-2559: {profit_2555_2559.sum()} THB")

# Calculate profit for years 2560-2562
df_2560_2562 = filtered_df[filtered_df['year'].between(2560, 2562)]
profit_2560_2562 = (df_2560_2562['production_ton'] * 1000) * 120 * 0.3
#print(f"Profit for 2560-2562: {profit_2560_2562.sum()} THB")

# Calculate total profit
total_profit = profit_2555_2559.sum() + profit_2560_2562.sum()
print(f"Total Profit: {total_profit} THB")

Total Profit: 5076935000.0 THB


### Question 4

Form question 3, display the dataframe with 'year', 'production_ton', 'income', 'profit_thb' column


In [17]:
# Write you code and display question 4 result here.

# Filter rows for the specified product and region
filtered_df = df[
    (df['product'] == 'ข้าวโพดฝักอ่อน') &
    (df['province'] == 'ภาคเหนือ') &
    (df['year'].between(2555, 2562))
]

# Define profit rates and selling prices for different year ranges
filtered_df['income'] = filtered_df.apply(
    lambda row: (row['production_ton'] * 1000) * 
                (50 if row['year'] <= 2559 else 120), axis=1
)
filtered_df['profit_thb'] = filtered_df.apply(
    lambda row: row['income'] * (0.5 if row['year'] <= 2559 else 0.3), axis=1
)

# Display the DataFrame with the required columns
result_df = filtered_df[['year', 'production_ton', 'income', 'profit_thb']]
print(result_df)

       year  production_ton        income   profit_thb
11690  2555         24741.0  1.237050e+09  618525000.0
11691  2556         25371.0  1.268550e+09  634275000.0
11692  2557         21788.0  1.089400e+09  544700000.0
11693  2558         20499.0  1.024950e+09  512475000.0
11694  2559         19332.0  9.666000e+08  483300000.0
11695  2560         21329.0  2.559480e+09  767844000.0
11696  2561         21757.0  2.610840e+09  783252000.0
11697  2562         20349.0  2.441880e+09  732564000.0


C:\Users\pammy\AppData\Local\Temp\ipykernel_23988\3721350822.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['income'] = filtered_df.apply(
C:\Users\pammy\AppData\Local\Temp\ipykernel_23988\3721350822.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['profit_thb'] = filtered_df.apply(


### Question 5

We plan to invest in growing soybeans (ถั่วเหลือง) which province should we invest.

We looking for
- high protential area (high havest_rate)
- we want market share only 20% but production_ton should be more than 2000 in the past (2550 - 2562)



In [21]:

# Write you code and display question 5 result here.

# Filter data for soybean and years 2550-2562
soybean_df = df[
    (df['product'] == 'ถั่วเหลือง') &
    (df['year'].between(2550, 2562))
]

# Calculate harvest rate for each record
soybean_df['harvest_rate'] = (soybean_df['area_harvest_rai'] / soybean_df['area_plant_rai']) * 100

# Aggregate data by province
province_summary = soybean_df.groupby('province').agg(
    total_production_ton=('production_ton', 'sum'),
    avg_harvest_rate=('harvest_rate', 'mean')
).reset_index()

# Filter provinces based on the criteria
filtered_provinces = province_summary[
    (province_summary['total_production_ton'] > 2000) &
    (province_summary['total_production_ton'] > 10_000 * 0.2)
]

# Sort by average harvest rate in descending order
filtered_provinces = filtered_provinces.sort_values(by='avg_harvest_rate', ascending=False).reset_index(drop=True)

# Add an index column starting from 1
filtered_provinces.index = filtered_provinces.index + 1
filtered_provinces.index.name = 'ranking'

# Display the result
print(filtered_provinces)


                      province  total_production_ton  avg_harvest_rate
ranking                                                               
1                         แพร่            124649.000         99.411723
2                   แม่ฮ่องสอน            216298.000         99.150895
3                   ฉะเชิงเทรา              8038.000         99.007171
4                        ลำพูน              3471.967         98.941240
5                     เชียงราย             68852.000         98.814047
6                    เพชรบูรณ์              8959.000         98.493804
7                    เชียงใหม่            180564.000         98.471452
8                      ภาคกลาง             49931.948         98.314104
9                         น่าน             61758.000         98.175079
10                         ตาก             71097.000         98.137804
11                    จันทบุรี              3953.000         98.072065
12                   นครสวรรค์              2021.000         97.902366
13    

C:\Users\pammy\AppData\Local\Temp\ipykernel_23988\3359306738.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  soybean_df['harvest_rate'] = (soybean_df['area_harvest_rai'] / soybean_df['area_plant_rai']) * 100
